changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: GitHub and Project Setup
      labels:
        - github
    - title: Other Changes
      labels:
        - "*"
